version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7-fpm
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./src:/src
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    mysql:
        image: mariadb
        restart: always
        ports:
            - "6603:3306"
        environment:
            MYSQL_DATABASE: lumen
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - my-datavolume:/var/lib/mysql

volumes:
    my-datavolume: